# Generated by Django 5.2 on 2025-04-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="reflection",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="tags",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
